version: 0.2
phases:
 install:
   commands:
     - npm install
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm run-script build
 post_build:
   commands:
     - echo "post_build step"
     - cd build
     - aws s3 sync --delete . "s3://daddybuffalo.com"