version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo "build step"
     - npm run-script build
 post_build:
   commands:
     - echo "post_build step"
     - aws s3 sync --delete build/* "s3://daddybuffalo.com"