version: 0.2
phases:
 install:
   commands:
     - npm install
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm run-script build
 post_build:
   commands:
     - cd build
     - 'aws s3 sync --delete . $BUILD_OUTPUT_BUCKET'
     - zip -r ../package.zip *
    #  Oh man look who's using AWS lmao
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - package.zip
  discar-paths: yes